apiVersion: v1
kind: Pod
metadata:
  name: test-downwardapi-volume
  labels:
    zone: us-est-coast
    cluster: test-cluster1
    rack: rack-22
spec:
  containers:
    - name: nginx-container
      image: nginx
      volumeMounts:
        - name: poduid
          mountPath: /etc/poduid
        - name: podinfo
          mountPath: /etc/podinfo
        - name: podname
          mountPath: /etc/podname
        - name: podnamespace
          mountPath: /etc/podnamespace
    - name: shell
      image: busybox
      stdin: true
      tty: true
      volumeMounts:
        - name: poduid
          mountPath: /etc/poduid
        - name: podinfo
          mountPath: /etc/podinfo
        - name: podname
          mountPath: /etc/podname
        - name: podnamespace
          mountPath: /etc/podnamespace
  volumes:
    - name: podinfo
      projected:
        sources:
        - downwardAPI:
            items:
              - path: "labels"
                fieldRef:
                  fieldPath: metadata.labels
    - name: poduid
      projected:
        sources:
        - downwardAPI:
            items:
              - path: "poduid"
                fieldRef:
                  fieldPath: metadata.uid
    - name: podname
      projected:
        sources:
        - downwardAPI:
            items:
              - path: "podname"
                fieldRef:
                  fieldPath: metadata.name
    - name: podnamespace
      projected:
        sources:
        - downwardAPI:
            items:
              - path: "podnamespace"
                fieldRef:
                  fieldPath: metadata.namespace
